name: GitHub-Hosted Runners Demo

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print System INFO
        run: |
          echo "OS: Ubuntu"
          hostname
          whoami

      - name: Print Versions
        run: |
          docker --version
          python3 --version
          node --version
          git --version

  windows:
    runs-on: windows-latest
    steps:
      - name: Print System INFO
        run: |
          echo "OS: Windows"
          hostname
          whoami

  macos:
    runs-on: macos-latest
    steps:
      - name: Print System INFO
        run: |
          echo "OS: MacOS"
          hostname
          whoami
