name: PR Check

on:
  workflow_dispatch:
  #pull_request:
    #branches: [main]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: 'echo "PR check running for branch: ${{ github.head_ref }}"'
