name: Use Composite Action

on:
  push:
    branches:
      - main

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup-and-greet action
        id: greet
        uses: ./.github/actions/setup-and-greet
        with:
          name: "Atul"
          language: "en"

      - name: Verify output
        run: 'echo "Greeting Completed: ${{ steps.greet.outputs.greeted }}"'
